version: '3'

services:
  rosject:
    image: cali_base:latest
    container_name: cali_project
    network_mode: host
    privileged: true
    volumes:
      # ---------------------------------------------------------------------
      # Remember that to allow docker to public GUI tools on your computer
      # you have to run "xhost +local:root". To disallow, "xhost -local:root"
      #
      # The volume below allows the container to have access to the
      # "physical display". If the DISPLAY variable is :0(echo $DISPLAY), then the graphical
      # things will be written at /tmp/.X11-unix/X0
      # ---------------------------------------------------------------------
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY # Forward the DISPLAY variable of the host to the container
      - QT_X11_NO_MITSHM=1 # Taken from https://answers.ros.org/question/391195/using-rviz-in-docker/?answer=391504#post-id-391504

    # entrypoint: ["/bin/bash", "-c"]
    command:
      - bash
      - -c
      - |
          source /opt/ros/melodic/setup.bash
          source /catkin_ws/devel/setup.bash
          source /usr/share/gazebo/setup.sh
          roslaunch rover_autonav cali_ecst_lab.launch --screen
